README.md

You know, for those first-time users ;)
Seriously, this will help the repo show up in GitHub searches for things like "SMS API", or "telephony framework".

Explain what Plivo is

---

lib/plivo.js

Added missing delete_recording API method into plivo.js

added delete_recording endpoint

---

gulpfile.js
lib/resources/accounts.js
test/accounts.js

- fix enabled flag params parsing in subaccount create
- Add Test cases for create subaccount
- Implemented Throw errors for test case errors

Fix create subaccount function to enable subaccount while creating

---

lib/resources/messages.js
test/messages.js

adding powerpack UUID as a param in send message

Feature powerpack

---

CHANGELOG.md
lib/base.js
package.json

Change: all list function will print the meta object.

by default print the meta on list function

---

CHANGELOG.md
examples/messages.js
lib/resources/messages.js
package.json
test/messages.js

list media
get media
delete media
send mms

MMS changes

---

CHANGELOG.md
lib/rest/utils.js
package.json

JIRA: https://plivo-team.atlassian.net/browse/SUP-1119

Skip end_time param from snake casing

---

CHANGELOG.md
lib/base.js
lib/resources/applications.js
lib/resources/call.js
lib/resources/conferences.js
lib/resources/endpoints.js
lib/resources/recordings.js
lib/rest/request.js
package.json

Voice requests retry logic

---

CHANGELOG.md
README.md
examples/lookup.js
lib/resources/lookup.js
lib/rest/request-test.js
package.json
test/lookup.js

Lookup API: Change endpoint and response

---

CHANGELOG.md
README.md
lib/rest/axios.js
lib/rest/request.js
lib/utils/exceptions.js
lib/utils/restException.js
package.json

https://www.npmjs.com/advisories/1594
@huzaif-plivo Please have a look on this. Do a round of sanity on this too

axios  version upgrade

---

CHANGELOG.md
lib/resources/media.js
lib/rest/axios.js
package.json

introduced the new flag multipart and handled the form data in the of PR https://github.com/plivo/plivo-node/pull/178/files#diff-bc5c4519a958f0fa13a4f62b9f3d23e916c7250f0ec1784a6a0e4fe665187979R35.  Bcz of this mms media upload is failed. 
Part of Fix:
- Added new flag on mms media upload function
- Handled the client side exception, In case file not found.
- Handled if file type is array

media upload fix

---

CHANGELOG.md
lib/rest/axios.js
package.json

https://github.com/plivo/plivo-node/issues/204
https://github.com/plivo/plivo-node/issues/207
cc @likithplivo

Voice get request and Exception handle

---

CHANGELOG.md
package.json
types/rest/client.d.ts

https://github.com/plivo/plivo-node/issues/210
cc @huzaif-plivo

typescript import fix

---

CHANGELOG.md
lib/rest/axios.js
package.json

1) Timeout removed for messaging
2) Response undefined fix

customer issue fix

---

CHANGELOG.md
lib/resources/profile.js
lib/rest/client-test.js
lib/rest/client.js
lib/rest/request-test.js
package.json
test/profile.js

profile api change

---

CHANGELOG.md
package.json
types/resources/call.d.ts

fix response type for make call

---

.github/workflows/unitTests.yml
CHANGELOG.md
lib/resources/endpoints.js
package.json

https://github.com/plivo/plivo-node/issues/268

removed duplicate response

---

CHANGELOG.md
lib/resources/brand.js
lib/rest/request-test.js
package.json
test/brand.js

Brand Usecase

---

.gitignore
CHANGELOG.md
Dockerfile
Makefile
README.md
docker-compose.yml
lib/resources/messages.js
lib/rest/request-test.js
package.json
setup_sdk.sh
test/messages.js
types/resources/messages.d.ts

Jira: https://plivo-team.atlassian.net/browse/SMS-5025
Also added a docker setup for local development

SMS-5025: Add Requester IP to Get and List Messages

---

CHANGELOG.md
lib/resources/messages.js
package.json
setup_sdk.sh
types/resources/messages.d.ts

Jira: https://plivo-team.atlassian.net/browse/SMS-5391

SMS-5391: Add replaced_sender in MDR Get and List apis

---

.gitignore
CHANGELOG.md
package.json

To address [CVE-2023-0842](https://github.com/advisories/GHSA-776f-qx25-q3cc)

Updating xml2js

---

CHANGELOG.md
Makefile
lib/resources/messages.js
lib/rest/request-test.js
package.json
test/messages.js

Jira: https://plivo-team.atlassian.net/browse/SMS-6010

SMS-6010: Add DLT Params to Send and Get Message APIs

---

CHANGELOG.md
lib/rest/axios.js
package.json

Changes:
- Added HTTP/HTTPS agent configuration with connection pooling (maxSockets: 100, keepAlive: true) to prevent progressive API latency increase.
- Fixed memory leak in retryWrapper interceptors that accumulated over time, causing CPU spikes and performance degradation.
- Improved resource cleanup in voice request handling to maintain stable memory usage and eliminate the need for server restarts.

VT-9003: Plivo SDK API Response Time Degrades Over Time

---

CHANGELOG.md
lib/utils/plivoxml.js
package.json

Added support for two new elements - `callerId` and `callerName` - in Number and User element in Dial XML

VT-9005: Support new param in Dial XML
